version: '2'

services:
  app:
    build: ./web
    ports:
      - 8888:8888
    links:
      - mongo
    volumes:
      # - data:/go
      # - ${ROOT_DIR}:/go/src/app
      - ../:/go/src/app
    command: go run server.go
    container_name: snicket-web

  mongo:
    image: mongo:3.4.0
    # restart: always
    volumes:
    - mongo-data:/data/db
    container_name: snicket-mongo

volumes:
  # data:
  #   driver: local
  mongo-data:
    driver: local
